### PR TITLE
db default config

### PR DESCRIPTION
**Pull request by ralic**

### CODE REVIEW

**Comment by josephspurrier** [comment]
These are old files. I just moved the structure around and the new config file is here: https://github.com/blue-jay/blueprint/blob/master/env.json.example.

**Comment by ralic** [comment]
Hi Joseph,

This is an awesome project. Any features in mind and wish that I may
contribute some in the project.

Thanks.

​Best regards,
Ralic Lo
*------------------------------------------------------------------------*
*---*
Phone: 408-609-7628
Email: RalicLo@gmail.com
*------------------------------------------------------------------------*
*---*

*--*

**Comment by josephspurrier** [comment]
Hi @ralic, thanks so much. You can start on #5, #24, and #29 if you're interested. Those are going to be some of the more difficult ones.

**Comment by josephspurrier** [comment]
I also added a new milestone, Phase Charlie, for Blueprint and Jay.

https://github.com/blue-jay/blueprint/milestones/Phase%20Charlie
https://github.com/blue-jay/jay/milestones/Phase%20Charlie

Any help on testing would be greatly appreciated. If you see any issues or have suggestions for the documentation, you can comment create issues and pull requests here: https://github.com/blue-jay/blue-jay.github.io.hugo

**Pull request closed without merging**
